name: ipfs_http_rpc
description: Yet another IPFS (HTTP RPC) client implementation for Dart. This package allows easy access to IPFS methods over HTTP with clear documentation.
version: 0.0.3
homepage: https://github.com/tobimd/ipfs_http_rpc.git
repository: https://github.com/tobimd/ipfs_http_rpc

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
